key,default_value
userAgent,"aws-cli/1.11.139 Python/3.6.3 Linux/4.13.0-38-generic botocore/1.6.6"
eventID,"0dc40d8b-f1a9-4832-839a-5bae6abb5bee"
errorMessage,"An unknown error occurred"
userIdentity_type,"IAMUser"
userIdentity_principalId,"AIDADO2GQD0K8TEF7KW1V"
userIdentity_arn,"arn:aws:iam::811596193553:user/Level6"
userIdentity_accountId,"811596193553"
userIdentity_accessKeyId,"AKIA3Z2XBVUDFQ9TU4MD"
userIdentity_userName,"Level6"
eventType,"AwsApiCall"
errorCode,"AccessDeniedException"
sourceIPAddress,"150.5.17.8"
eventName,"DescribeMyUserProfile"
eventSource,"opsworks.amazonaws.com"
recipientAccountId,"811596193553"
requestParameters,"None"
awsRegion,"us-west-2"
requestID,"23d96b63-46e0-11e8-99e3-c9a1224f0bcd"
responseElements,"None"
eventVersion,"1.05"
eventTime,"2018-04-23T10:21:52Z"
