key,default_value
userAgent,"Botocore/1.16.26 Python/2.7.18 Linux/5.4.0-2-amd64"
eventID,"353420-cb71-4c50-acbf-009562b37945"
errorMessage,"User: arn:aws:iam::811596193553:user/backup is not authorized to perform: servicecatalog:DescribeProvisioningArtifact on resource: arn:aws:servicecatalog:us-east-1:811596193553:*/*"
userIdentity_type,"IAMUser"
userIdentity_principalId,"AIDA9BO36HFBHKGJAO9C1"
userIdentity_arn,"arn:aws:iam::811596193553:user/backup"
userIdentity_accountId,"811596193553"
userIdentity_accessKeyId,"AKIA01U43UX3RBRDXF4Q"
userIdentity_userName,"backup"
eventType,"AwsApiCall"
errorCode,"AccessDenied"
sourceIPAddress,"251.105.254.1"
eventName,"DescribeProvisioningArtifact"
eventSource,"servicecatalog.amazonaws.com"
recipientAccountId,"811596193553"
requestParameters,"None"
awsRegion,"us-east-1"
requestID,"47ff8980-744c-47ec-ba21-b3890ba7c95d"
responseElements,"None"
eventVersion,"1.05"
eventTime,"2020-06-10T05:34:15Z"
