key,default_value
userAgent,"Botocore/1.16.26 Python/2.7.18 Linux/5.4.0-2-amd64"
eventID,"0e6a52a3-1b7d-4f6a-bcfc-6cf45cbf371c"
errorMessage,"User: arn:aws:iam::811596193553:user/backup is not authorized to perform: sagemaker:ListHumanTaskUis"
userIdentity_type,"IAMUser"
userIdentity_principalId,"AIDA9BO36HFBHKGJAO9C1"
userIdentity_arn,"arn:aws:iam::811596193553:user/backup"
userIdentity_accountId,"811596193553"
userIdentity_accessKeyId,"AKIA01U43UX3RBRDXF4Q"
userIdentity_userName,"backup"
eventType,"AwsApiCall"
errorCode,"AccessDenied"
sourceIPAddress,"251.105.254.1"
eventName,"ListHumanTaskUis"
eventSource,"sagemaker.amazonaws.com"
recipientAccountId,"811596193553"
requestParameters,"None"
awsRegion,"us-east-1"
requestID,"274f7481-1384-4218-92b1-683b43210d99"
responseElements,"None"
eventVersion,"1.05"
eventTime,"2020-06-10T05:35:07Z"
