key,default_value
userAgent,"Botocore/1.12.25 Python/2.7.15 Linux/4.16.0-kali2-amd64"
eventID,"49a9dfa0-9a4a-41c9-8dbd-e87007350f0e"
errorMessage,"An unknown error occurred"
userIdentity_type,"IAMUser"
userIdentity_principalId,"AIDADO2GQD0K8TEF7KW1V"
userIdentity_arn,"arn:aws:iam::811596193553:user/Level6"
userIdentity_accountId,"811596193553"
userIdentity_accessKeyId,"AKIA3Z2XBVUDFQ9TU4MD"
userIdentity_userName,"Level6"
eventType,"AwsApiCall"
errorCode,"InternalFailure"
sourceIPAddress,"9.245.1.85"
eventName,"ListContainerInstances"
eventSource,"ecs.amazonaws.com"
recipientAccountId,"811596193553"
requestParameters,"None"
awsRegion,"us-east-1"
requestID,"420249b57-d249-11e8-957c-f80a39444a44"
responseElements,"None"
eventVersion,"1.04"
eventTime,"2018-10-17T20:15:30Z"
