key,default_value
userAgent,"Botocore/1.16.26 Python/2.7.18 Linux/5.4.0-2-amd64"
eventID,"272afd4f-d436-4c6b-b588-931b2b3c859e"
errorMessage,"User: arn:aws:iam::811596193553:user/backup is not authorized to perform: sagemaker:ListTrials"
userIdentity_type,"IAMUser"
userIdentity_principalId,"AIDA9BO36HFBHKGJAO9C1"
userIdentity_arn,"arn:aws:iam::811596193553:user/backup"
userIdentity_accountId,"811596193553"
userIdentity_accessKeyId,"AKIA01U43UX3RBRDXF4Q"
userIdentity_userName,"backup"
eventType,"AwsApiCall"
errorCode,"AccessDenied"
sourceIPAddress,"251.105.254.1"
eventName,"ListTrials"
eventSource,"sagemaker.amazonaws.com"
recipientAccountId,"811596193553"
requestParameters,"None"
awsRegion,"us-east-1"
requestID,"c29c092e-50d9-4c8c-99fb-8fd67a56a1da"
responseElements,"None"
eventVersion,"1.05"
eventTime,"2020-06-10T05:35:10Z"
