key,default_value
userAgent,"Botocore/1.16.26 Python/2.7.18 Linux/5.4.0-2-amd64"
eventID,"6ec5d6e9-3cd2-4741-9de7-a0744b7cefc9"
errorMessage,"User: arn:aws:iam::811596193553:user/backup is not authorized to perform: sagemaker:ListMonitoringExecutions"
userIdentity_type,"IAMUser"
userIdentity_principalId,"AIDA9BO36HFBHKGJAO9C1"
userIdentity_arn,"arn:aws:iam::811596193553:user/backup"
userIdentity_accountId,"811596193553"
userIdentity_accessKeyId,"AKIA01U43UX3RBRDXF4Q"
userIdentity_userName,"backup"
eventType,"AwsApiCall"
errorCode,"AccessDenied"
sourceIPAddress,"251.105.254.1"
eventName,"ListMonitoringExecutions"
eventSource,"sagemaker.amazonaws.com"
recipientAccountId,"811596193553"
requestParameters,"None"
awsRegion,"us-east-1"
requestID,"20dbcb32-3108-467f-a632-ab64eb2a2a86"
responseElements,"None"
eventVersion,"1.05"
eventTime,"2020-06-10T05:35:07Z"
