key,default_value
userAgent,"Boto3/1.9.210 Python/2.7.10 Darwin/18.7.0 Botocore/1.12.210"
eventID,"db1b9709-d847-4d75-8571-364423f0b97d"
errorMessage,"User: arn:aws:iam::811596193553:user/backup is not authorized to perform: organizations:ListAWSServiceAccessForOrganization on resource: *"
userIdentity_type,"IAMUser"
userIdentity_principalId,"AIDA9BO36HFBHKGJAO9C1"
userIdentity_arn,"arn:aws:iam::811596193553:user/backup"
userIdentity_accountId,"811596193553"
userIdentity_accessKeyId,"AKIA01U43UX3RBRDXF4Q"
userIdentity_userName,"backup"
eventType,"AwsApiCall"
errorCode,"AccessDenied"
sourceIPAddress,"213.253.166.5"
eventName,"ListAWSServiceAccessForOrganization"
eventSource,"organizations.amazonaws.com"
recipientAccountId,"811596193553"
requestParameters,"None"
awsRegion,"us-east-1"
requestID,"865251-856a-4e70-b4ac-d6cb03f26f14"
responseElements,"None"
eventVersion,"1.05"
eventTime,"2019-10-19T23:49:25Z"
