key,default_value
userAgent,"Botocore/1.16.26 Python/2.7.18 Linux/5.4.0-2-amd64"
eventID,"c2418f0e-3c25-4f66-b6b2-fccb6fb800ea"
errorMessage,"User: arn:aws:iam::811596193553:user/backup is not authorized to perform: sagemaker:ListExperiments"
userIdentity_type,"IAMUser"
userIdentity_principalId,"AIDA9BO36HFBHKGJAO9C1"
userIdentity_arn,"arn:aws:iam::811596193553:user/backup"
userIdentity_accountId,"811596193553"
userIdentity_accessKeyId,"AKIA01U43UX3RBRDXF4Q"
userIdentity_userName,"backup"
eventType,"AwsApiCall"
errorCode,"AccessDenied"
sourceIPAddress,"251.105.254.1"
eventName,"ListExperiments"
eventSource,"sagemaker.amazonaws.com"
recipientAccountId,"811596193553"
requestParameters,"None"
awsRegion,"us-east-1"
requestID,"0ad07400-dc83-41b8-a285-874ad4af13f8"
responseElements,"None"
eventVersion,"1.05"
eventTime,"2020-06-10T05:35:07Z"
