key,default_value
userAgent,"Botocore/1.16.26 Python/2.7.18 Linux/5.4.0-2-amd64"
eventID,"b52697ac-b290-4fc8-97d5-904ff7b208105"
errorMessage,"User: arn:aws:iam::811596193553:user/backup is not authorized to perform: dynamodb:ListContributorInsights on resource: arn:aws:dynamodb:us-east-1:811596193553:table/*"
eventCategory,"Management"
userIdentity_type,"IAMUser"
userIdentity_principalId,"AIDA9BO36HFBHKGJAO9C1"
userIdentity_arn,"arn:aws:iam::811596193553:user/backup"
userIdentity_accountId,"811596193553"
userIdentity_accessKeyId,"AKIA01U43UX3RBRDXF4Q"
userIdentity_userName,"backup"
eventType,"AwsApiCall"
errorCode,"AccessDenied"
sourceIPAddress,"251.105.254.1"
eventName,"ListContributorInsights"
eventSource,"dynamodb.amazonaws.com"
managementEvent,"True"
recipientAccountId,"811596193553"
requestParameters,"None"
awsRegion,"us-east-1"
readOnly,"False"
requestID,"BPMGH7A7QT6EMGG2BLD3K8QUHRVV4KQNSO5AEMVJF66Q9ASUAAJG"
responseElements,"None"
eventVersion,"1.07"
eventTime,"2020-06-10T05:30:35Z"
resources,"[]"
