key,default_value
userAgent,"Botocore/1.16.26 Python/2.7.18 Linux/5.4.0-2-amd64"
eventID,"7ce22058-1f58-472a-8be7-29fd2f728661"
errorMessage,"User: arn:aws:iam::811596193553:user/backup is not authorized to perform: health:DescribeEventsForOrganization on resource: *"
userIdentity_type,"IAMUser"
userIdentity_principalId,"AIDA9BO36HFBHKGJAO9C1"
userIdentity_arn,"arn:aws:iam::811596193553:user/backup"
userIdentity_accountId,"811596193553"
userIdentity_accessKeyId,"AKIA01U43UX3RBRDXF4Q"
userIdentity_userName,"backup"
eventType,"AwsApiCall"
errorCode,"AccessDenied"
sourceIPAddress,"251.105.254.1"
eventName,"DescribeEventsForOrganization"
eventSource,"health.amazonaws.com"
recipientAccountId,"811596193553"
requestParameters,"None"
awsRegion,"us-east-1"
requestID,"dd78682d-87e1-4428-8603-9bfe6aef0283"
responseElements,"None"
eventVersion,"1.05"
eventTime,"2020-06-10T05:30:46Z"
