key,default_value
userAgent,"Boto3/1.10.19 Python/3.6.8 Linux/4.15.0-66-generic Botocore/1.13.19"
eventID,"7482a7a8-416f-4460-a500-7b6d69e0b814"
errorMessage,"User: arn:aws:iam::811596193553:user/backup is not authorized to perform: ds:GetDirectoryLimits"
userIdentity_type,"IAMUser"
userIdentity_principalId,"AIDA9BO36HFBHKGJAO9C1"
userIdentity_arn,"arn:aws:iam::811596193553:user/backup"
userIdentity_accountId,"811596193553"
userIdentity_accessKeyId,"AKIA01U43UX3RBRDXF4Q"
userIdentity_userName,"backup"
eventType,"AwsApiCall"
errorCode,"AccessDenied"
sourceIPAddress,"4.237.1.155"
eventName,"GetDirectoryLimits"
eventSource,"ds.amazonaws.com"
recipientAccountId,"811596193553"
requestParameters,"None"
awsRegion,"us-east-1"
requestID,"95fcc841-b37a-4d72-8e60-669bc159d1a6"
responseElements,"None"
eventVersion,"1.05"
eventTime,"2019-11-20T07:43:11Z"
