key,default_value
userAgent,"Boto3/1.4.4 Python/2.7.13 Darwin/15.6.0 Botocore/1.5.14"
eventID,"fdc778f7-f05b-407b-8e2a-144b35b96045"
errorMessage,"User: arn:aws:iam::811596193553:user/backup is not authorized to perform: dynamodb:ListTables on resource: *"
userIdentity_type,"IAMUser"
userIdentity_principalId,"AIDA9BO36HFBHKGJAO9C1"
userIdentity_arn,"arn:aws:iam::811596193553:user/backup"
userIdentity_accountId,"811596193553"
userIdentity_accessKeyId,"AKIA1ZBTOEKWKVHP6GHZ"
userIdentity_userName,"backup"
eventType,"AwsApiCall"
errorCode,"AccessDenied"
sourceIPAddress,"49.251.42.250"
eventName,"ListTables"
eventSource,"dynamodb.amazonaws.com"
recipientAccountId,"811596193553"
requestParameters,"None"
awsRegion,"us-east-1"
requestID,"VEMF8KGEKAFAM1KFOLP8GVNCURVV4KQNSO5AEMVJF66Q9ASUAAJG"
responseElements,"None"
eventVersion,"1.05"
eventTime,"2017-02-28T22:14:41Z"
