key,default_value
userAgent,"Boto3/1.7.48 Python/3.5.3 Linux/4.9.0-7-amd64 Botocore/1.10.48"
eventID,"f9c7323e-08e5-410b-9c93-fe687146af748"
errorMessage,"User: arn:aws:iam::811596193553:user/backup is not authorized to perform: iam:PutUserPolicy on resource: user flaws"
userIdentity_type,"IAMUser"
userIdentity_principalId,"AIDA9BO36HFBHKGJAO9C1"
userIdentity_arn,"arn:aws:iam::811596193553:user/backup"
userIdentity_accountId,"811596193553"
userIdentity_accessKeyId,"AKIA01U43UX3RBRDXF4Q"
userIdentity_userName,"backup"
eventType,"AwsApiCall"
errorCode,"AccessDenied"
sourceIPAddress,"82.247.92.218"
eventName,"PutUserPolicy"
eventSource,"iam.amazonaws.com"
recipientAccountId,"811596193553"
requestParameters,"None"
awsRegion,"us-east-1"
requestID,"475a4fe5-ce4b-11e8-b8d6-a7951e68fc2c"
responseElements,"None"
eventVersion,"1.05"
eventTime,"2018-10-12T18:18:55Z"
